# permissions for end users to edit fqdnnetworkpolicies.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fqdnnetworkpolicy-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fqdn-operator
    app.kubernetes.io/part-of: fqdn-operator
    app.kubernetes.io/managed-by: kustomize
  name: fqdnnetworkpolicy-editor-role
rules:
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - twistedsolutions.se
  resources:
  - fqdnnetworkpolicies/status
  verbs:
  - get
